// <auto-generated />
using System;
using AGREGAMENTO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGREGAMENTO.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240116204151_Colaborador-migration")]
    partial class Colaboradormigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AGREGAMENTO.Models.AgregadosAcompanhamentoModel", b =>
                {
                    b.Property<int>("IdSerede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSerede"), 1L, 1);

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("GestorCentroDeCusto")
                        .HasColumnType("int");

                    b.Property<int>("Pagamento")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("SituacaoColaborador")
                        .HasColumnType("int");

                    b.Property<string>("Termo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UF")
                        .HasColumnType("int");

                    b.HasKey("IdSerede");

                    b.ToTable("Agregados");
                });

            modelBuilder.Entity("AGREGAMENTO.Models.CadastroDeFabricanteModel", b =>
                {
                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataDaAcao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSerede")
                        .HasColumnType("int");

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.HasKey("Ativo");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("AGREGAMENTO.Models.CadastroDeValoresModel", b =>
                {
                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataDaAcao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSerede")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Estado");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("AGREGAMENTO.Models.DadosDoColaboradorModel", b =>
                {
                    b.Property<int>("IdSerede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSerede"), 1L, 1);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentroDeCusto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gestor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SituacaoDoColaborador")
                        .HasColumnType("bit");

                    b.HasKey("IdSerede");

                    b.ToTable("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
